export const AppActionTypes = {
  SET_TABLE_HEADERS: 'SET_TABLE_HEADERS',
  SET_TABLE_DATA: 'SET_TABLE_DATA',
  CLEAR_TABLE_DATA: 'CLEAR_TABLE_DATA',
  SET_VENDOR_DATA: 'SET_VENDOR_DATA',
  SET_SELECTED_ROW: 'SET_SELECTED_ROW',
  TOGGLE_MODAL: 'TOGGLE_MODAL',
};
